# Generated by Django 3.0.5 on 2020-04-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='42', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('att', 'attended'), ('in_att', 'in attendance'), ('wai', 'waiting')], default='wai', max_length=10)),
                ('queue', models.ForeignKey(default='42', on_delete=django.db.models.deletion.CASCADE, to='ploja.Queue')),
            ],
        ),
    ]
